services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: flashsale_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword123! # Keep this safe!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: